services:
  mongo:
    image: mongo:latest
    container_name: mymongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - /mongodb_data:/data/db
      - ./data:/shared_data
      - ./python_scripts:/shared_scripts_py
      - ./js_scripts:/shared_scripts_js

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin

    depends_on:
      - mongo

volumes:
  mongodb_data:
